### PR TITLE
Fix firmware build

### PR DESCRIPTION
**Pull request by bbadrignans**
Tested on v2.6.0 nRF Connect SDK, on a Debian 12.
I think workdir in cli/cmd/zigbee/firmware/build.go should be an absolute path.
Remove useless environment variables in cli/runner/cmd.go and fix ldLibraryPath.
Not sure it will work out of my setup.

### CODE REVIEW

**Comment by ffenix113** [comment]
Hello @bbadrignans !

Thank you for the PR. Could you please check if all of the changes are necessary?
Meaning can you try to remove everything that is not impacting fixing your issue. Or are all changes are necessary to build on your machine?

**Comment by bbadrignans** [comment]
Hello @ffenix113 !
Everything that I added is necessary to build on my environment.
Everything that I removed can be kept, it is not used in my build.
So if you prefer you can keep what I removed for the moment. Just note that ldLibraryPath is set using ncsCombinedPath but it should be ncsToolchainPath.

**Comment by ffenix113** [comment]
That sounds good: if you could leave just needed change and, if you would have time for, update the wrong variable used in ldLibraryPath. 

Thank you for again for the PR!

**Comment by ffenix113** [comment]
Thank you for the PR!
I've removed env changes, leaving only the fixed variable usage. 

I will work on some changes to runner, to better search for Zephyr and toolchain, hopefully providing an automatic way.

**Pull request merged**
